[package]
name = "lefi"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
thiserror = "1.0"
rustatlas = { path = "../rustatlas"}
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2.19"
rand = "0.8"
